### ISSUE TITLE
You need to include some adapter that implements __karma__.start method!

### ISSUE THREAD

**Issue by MikaAK** [iamJoeTaylor/karma-eslint#9]
This error pops up when i try to use this. The logs show up but this error occurs. Oddly this only happens if there are eslint errors when initially building. If the build passes lint initially it doesn't have this problem. 

Also, if there's an error after initially passing I get `Unhandled rejection Error: [object Object]`

As of right now setting `stopOnError: false` fixes this problem.

**Comment by nomve** [comment]
I think this error is confusing, but I guess it happens when you have linting errors and you configure eslint to stop on linting errors (which is the default). So the actual errors are that your code doesn't get pass the linter.

**Comment by BebeSparkelSparkel** [comment]
Having the same deal. It would be nice if it stopped the tests from running but kept watching the files for changes.
When there are linter errors and karma.conf.js has `singleRun: false,` the auto run on file change no longer works and the process has to be manually restarted.
